### ISSUE TITLE
Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency

### ISSUE THREAD

**Issue by vensing** [hexojs/hexo#4257]
## Check List

Please check followings before submitting a new issue.

- [ ] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [ ] I have already searched existing issues and they are not help  to me
- [ ] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than 8.6.0

## Expected behavior
build Normal  html

## Actual behavior
```
$ hexo clean && hexo g
(node:23020) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:23020) Warning: Accessing non-existent property 'column' of module exports inside circular dependency  
(node:23020) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
(node:23020) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency  
(node:23020) Warning: Accessing non-existent property 'column' of module exports inside circular dependency  
(node:23020) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
INFO  Deleted database.
INFO  Deleted public folder.
(node:21700) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:21700) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:21700) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
(node:21700) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(node:21700) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:21700) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
INFO  Start processing
INFO  Files loaded in 734 ms
(node:21700) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(node:21700) Warning: Accessing non-existent property 'column' of module exports inside circular dependency  
(node:21700) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
(node:21700) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency  
(node:21700) Warning: Accessing non-existent property 'column' of module exports inside circular dependency  
(node:21700) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
```

Build emtpy html.
It's build normal html when I use Node.js v12.14.1.
## How to reproduce?

* hexo clean 
* hexo g

## Environment & Settings

**Node.js & npm version**

```
node -v
v14.0.0

npm --v
v6.13.6
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
hexo -v
v4.2.0
```

**Your package.json `package.json`**

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "4.2.0"
  },
  "dependencies": {
    "hexo": "^4.2.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-feed": "^2.2.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-sitemap": "^2.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^2.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-sage-posts": "^0.0.1",
    "hexo-server": "^1.0.0"
  }
```

## Others

It's build normal html when I use Node.js v12.14.1.
Thanks, have a  nice day.

**Comment by SukkaW** [comment]
Uninstall hexo-sage-posts then try again?

**Comment by vensing** [comment]
> Uninstall hexo-sage-posts then try again?

It's still build empty html when I uninstall hexo-sage-post plugin. Others have the same problem when used nodejs stable version (v14.0) on travis CI build task. 

Please see the job log in https://www.travis-ci.org/github/AyagawaSeirin/Blog/builds/678004202 . 

Thanks, have a nice day.

**Comment by curbengh** [comment]
I can confirm this issue, being discussed in https://github.com/hexojs/hexo/issues/4260.

**Comment by vensing** [comment]
> I can confirm this compatibility issue with Node 14, being discussed in #4260.
> 
> > Uninstall hexo-sage-posts then try again?
> 
> I can replicate this issue in default hexo.

It's also appear in mongodb when used Node v14, see https://jira.mongodb.org/browse/NODE-2536. And fixed on node-mongodb-native [commit](https://github.com/mongodb/node-mongodb-native/commit/56a1b8aec3c4855b2709b27ff3127018cc2577aa).

**Comment by wizardforcel** [comment]
Yes, I also found this problem in Node 14, but not in Node 10 or 12.

**Comment by stevenjoezhang** [comment]
The warning message is from stylus
```
at Boolean.Node [as constructor] (/blog/node_modules/stylus/lib/nodes/node.js:44:23)
```

**Comment by vensing** [comment]
> The warning message is from stylus
> 
> ```
> at Boolean.Node [as constructor] (/blog/node_modules/stylus/lib/nodes/node.js:44:23)
> ```
> 
> To reproduce, run `const stylus = require('stylus');` with Node.js 14.0
> 
> There is no relevant issues opened here: https://github.com/stylus/stylus/issues

Thanks, I replicate the warning message. And build empty html which is caused by `hexo-fs` with Node.js 14.0

**Comment by SukkaW** [comment]
> And build empty html which is caused by `hexo-fs` with Node.js 14.0

The discussion of `hexo-fs` goes https://github.com/hexojs/hexo/issues/4260 and the fix is already implemented: https://github.com/hexojs/hexo-fs/pull/60

**Comment by tl3shi** [comment]
+1

**Comment by qianbinbin** [comment]
这就是node的兼容性吗？i了i了
```
brew uninstall node
brew install node@12
brew link --overwrite --force node@12
```
清净了

**Comment by YoshinoriN** [comment]
@vensing @wizardforcel @tl3shi 

We published [v4.2.1](https://github.com/hexojs/hexo/releases/tag/4.2.1).
v4.2.1 has included fixed compatible with Node 14.

Thanks :)

---

@qianbinbin

Node 12 works with hexo 4.2.0 or less than 4.2.0
Node 14 works with hexo 4.2.1+

**Comment by HyWell** [comment]
@YoshinoriN It doesn't seem to be fixed
![image](https://user-images.githubusercontent.com/21263451/82002822-707ebd80-9691-11ea-9749-622292fdc1db.png)

**Comment by stevenjoezhang** [comment]
@HyWell https://github.com/stylus/stylus/issues/2534

**Comment by vensing** [comment]
> @YoshinoriN It doesn't seem to be fixed
> ![image](https://user-images.githubusercontent.com/21263451/82002822-707ebd80-9691-11ea-9749-622292fdc1db.png)
The warning message is from stylus，see https://github.com/hexojs/hexo/issues/4257#issuecomment-618857837

**Comment by SkyYkb** [comment]
The problem still exists with Hexo 4.2.1:
<img width="682" alt="image" src="https://user-images.githubusercontent.com/44992049/84563236-9da3b600-ad8c-11ea-8858-061032f61a24.png">

**Comment by stevenjoezhang** [comment]
stylus/stylus#2534
stylus/stylus#2534
stylus/stylus#2534
